-- Use SQL insert statements to add any
-- starting/dummy data to your database tables

-- EXAMPLE:

 insert into "products"
   ("type", "gender", "name", "description", "details", "price", "color", "url")
   values
     ('jersey', 'm', 'Essential Jersey', 'The easy-care, wrinkle-free, and quick-drying properties of the Essential jersey’s fabric make this an ideal addition to your rotation of kit for both leisure rides and sportives. With a relaxed but not loose fit this piece remains equally adept on short training rides, social rides and longer days in the saddle. This piece is developed for all-day comfort.', 'details',155.00, 'Green Psych', 'https://assets.pasnormalstudios.com/14085/conversions/Mens-Essential-Jersey-Green-Psych-pdp-page.jpg?v=1678357773'),
     ('jersey', 'm', 'Essential Jersey', 'The easy-care, wrinkle-free, and quick-drying properties of the Essential jersey’s fabric make this an ideal addition to your rotation of kit for both leisure rides and sportives. With a relaxed but not loose fit this piece remains equally adept on short training rides, social rides and longer days in the saddle. This piece is developed for all-day comfort.
     ', 'details',155.00, 'Earth Psych', 'https://assets.pasnormalstudios.com/14094/conversions/Mens-Essential-Jersey-Earth-Psych-pdp-page.jpg?v=1678357879'),
     ('jersey', 'm', 'Essential Jersey', 'The easy-care, wrinkle-free, and quick-drying properties of the Essential jersey’s fabric make this an ideal addition to your rotation of kit for both leisure rides and sportives. With a relaxed but not loose fit this piece remains equally adept on short training rides, social rides and longer days in the saddle. This piece is developed for all-day comfort.', 'details',155.00, 'Purple Psych', 'https://assets.pasnormalstudios.com/14091/conversions/Mens-Essential-Jersey-Purple-Psych_Front-pdp-page.jpg?v=1678357849'),
     ('jersey', 'm', 'Essential Jersey', 'The easy-care, wrinkle-free, and quick-drying properties of the Essential jersey’s fabric make this an ideal addition to your rotation of kit for both leisure rides and sportives. With a relaxed but not loose fit this piece remains equally adept on short training rides, social rides and longer days in the saddle. This piece is developed for all-day comfort.', 'details',155.00, 'Stone Psyche', 'https://assets.pasnormalstudios.com/14088/conversions/Mens-Essential-Jersey-Stone-Psych_Front-pdp-page.jpg?v=1678357829'),
     ('jersey', 'm', 'Essential Jersey', 'The easy-care, wrinkle-free, and quick-drying properties of the Essential jersey’s fabric make this an ideal addition to your rotation of kit for both leisure rides and sportives. With a relaxed but not loose fit this piece remains equally adept on short training rides, social rides and longer days in the saddle. This piece is developed for all-day comfort.', 'details',155.00, 'Purple', 'https://assets.pasnormalstudios.com/388/conversions/PN_EssentialJErsey_Purple_4-5-pdp-page.jpg?v=1668716954'),
     ('jersey', 'm', 'Essential Jersey', 'The easy-care, wrinkle-free, and quick-drying properties of the Essential jersey’s fabric make this an ideal addition to your rotation of kit for both leisure rides and sportives. With a relaxed but not loose fit this piece remains equally adept on short training rides, social rides and longer days in the saddle. This piece is developed for all-day comfort.', 'details',155.00, 'Black', 'https://assets.pasnormalstudios.com/386/conversions/PN_EssentialJErsey_Black_4-5-pdp-page.jpg?v=1668716953'),
     ('jersey', 'm', 'Essential Jersey', 'The easy-care, wrinkle-free, and quick-drying properties of the Essential jersey’s fabric make this an ideal addition to your rotation of kit for both leisure rides and sportives. With a relaxed but not loose fit this piece remains equally adept on short training rides, social rides and longer days in the saddle. This piece is developed for all-day comfort.', 'details',155.00, 'Bright Yellow', 'https://assets.pasnormalstudios.com/6057/conversions/PN_Essential_Jersey_BrightYellow_4-5-pdp-page.jpg?v=1668717373'),
     ('jersey', 'm', 'Essential Jersey', 'The easy-care, wrinkle-free, and quick-drying properties of the Essential jersey’s fabric make this an ideal addition to your rotation of kit for both leisure rides and sportives. With a relaxed but not loose fit this piece remains equally adept on short training rides, social rides and longer days in the saddle. This piece is developed for all-day comfort.', 'details',155.00, 'Dark Turquoise', 'https://assets.pasnormalstudios.com/6054/conversions/PN_Essential_Jersey_Dark-Turquise_4-5-pdp-page.jpg?v=1668717373'),
     ('jersey', 'm', 'Essential Jersey', 'The easy-care, wrinkle-free, and quick-drying properties of the Essential jersey’s fabric make this an ideal addition to your rotation of kit for both leisure rides and sportives. With a relaxed but not loose fit this piece remains equally adept on short training rides, social rides and longer days in the saddle. This piece is developed for all-day comfort.', 'details',155.00, 'Earth', 'https://assets.pasnormalstudios.com/391/conversions/Man_Essential-Jerswey_Earth_4-5-pdp-page.jpg?v=1668716956'),
     ('jersey', 'm', 'Essential Jersey', 'The easy-care, wrinkle-free, and quick-drying properties of the Essential jersey’s fabric make this an ideal addition to your rotation of kit for both leisure rides and sportives. With a relaxed but not loose fit this piece remains equally adept on short training rides, social rides and longer days in the saddle. This piece is developed for all-day comfort.', 'details',155.00, 'White', 'https://assets.pasnormalstudios.com/5901/conversions/PN_EssentialJErsey_White_4-5-pdp-page.jpg?v=1668717355'),
     ('jersey', 'm', 'Essential Long Sleeve Jersey', 'The soft and luxurious Essential Long Sleeve Jersey is perfect for spring and autumn rides. The Essential Long Sleeve Jersey uses a soft 4-Way stretch fabric in a jersey cut with a more relaxed Essential fit. The grid fleece back of the fabric insulates and helps with moisture management. Even when adding layers over or under the jersey. The jersey is designed to combine seamlessly with the other elements in the Essential collection.', 'details',235.00, 'Off White', 'https://assets.pasnormalstudios.com/14259/conversions/Mens-Essential-Jersey-LS-Jersey-Off-White_Front-pdp-page.jpg?v=1678972792'),
     ('jersey', 'm', 'Essential Long Sleeve Jersey', 'The soft and luxurious Essential Long Sleeve Jersey is perfect for spring and autumn rides. The Essential Long Sleeve Jersey uses a soft 4-Way stretch fabric in a jersey cut with a more relaxed Essential fit. The grid fleece back of the fabric insulates and helps with moisture management. Even when adding layers over or under the jersey. The jersey is designed to combine seamlessly with the other elements in the Essential collection.', 'details',235.00, 'Olive', 'https://assets.pasnormalstudios.com/11147/conversions/Mens-Essential-Jersey-Dark-Olive-pdp-page.jpg?v=1668717883'),
     ('jersey', 'm', 'Essential Long Sleeve Jersey', 'The soft and luxurious Essential Long Sleeve Jersey is perfect for spring and autumn rides. The Essential Long Sleeve Jersey uses a soft 4-Way stretch fabric in a jersey cut with a more relaxed Essential fit. The grid fleece back of the fabric insulates and helps with moisture management. Even when adding layers over or under the jersey. The jersey is designed to combine seamlessly with the other elements in the Essential collection.', 'details',235.00, 'Clay', 'https://assets.pasnormalstudios.com/14271/conversions/Mens-Essential-Jersey-LS-Jersey-Clay_Front-pdp-page.jpg?v=1678973845'),
     ('jersey', 'm', 'Essential Long Sleeve Jersey', 'The soft and luxurious Essential Long Sleeve Jersey is perfect for spring and autumn rides. The Essential Long Sleeve Jersey uses a soft 4-Way stretch fabric in a jersey cut with a more relaxed Essential fit. The grid fleece back of the fabric insulates and helps with moisture management. Even when adding layers over or under the jersey. The jersey is designed to combine seamlessly with the other elements in the Essential collection.', 'details',235.00, 'Navy', 'https://assets.pasnormalstudios.com/11599/conversions/Mens-Essential-Jersey-Navy-pdp-page.jpg?v=1668717977'),
     ('jersey', 'm', 'Mechanism Jersey', 'Presented in its signature monochrome colourway, the Mechanism Jersey showcases the seamless integration of technical performance with fashionable aesthetics. Defined through its aerodynamic fit and use of lightweight fabric, the jersey is perfectly suited to competitive races or fast-paced training days while remaining a staple for your everyday summer rides.', 'details',200.00, 'Dusty Mauve', 'https://assets.pasnormalstudios.com/13658/conversions/Mens-Mechanism-Jersey-Mauve_Front-pdp-page.jpg?v=1677747196'),
     ('jersey', 'm', 'Mechanism Jersey', 'Presented in its signature monochrome colourway, the Mechanism Jersey showcases the seamless integration of technical performance with fashionable aesthetics. Defined through its aerodynamic fit and use of lightweight fabric, the jersey is perfectly suited to competitive races or fast-paced training days while remaining a staple for your everyday summer rides.', 'details',200.00, 'Deep Green', 'https://assets.pasnormalstudios.com/13743/conversions/Mens-Mechanism-Jersey-Green_Front-pdp-page.jpg?v=1677753733'),
     ('jersey', 'm', 'Mechanism Jersey', 'Presented in its signature monochrome colourway, the Mechanism Jersey showcases the seamless integration of technical performance with fashionable aesthetics. Defined through its aerodynamic fit and use of lightweight fabric, the jersey is perfectly suited to competitive races or fast-paced training days while remaining a staple for your everyday summer rides.', 'details',200.00, 'Dusty Teal', 'https://assets.pasnormalstudios.com/13646/conversions/Mens-Mechanism-Jersey-Dusty-Mauve_Front-pdp-page.jpg?v=1677746789'),
     ('jersey', 'm', 'Mechanism Jersey', 'Presented in its signature monochrome colourway, the Mechanism Jersey showcases the seamless integration of technical performance with fashionable aesthetics. Defined through its aerodynamic fit and use of lightweight fabric, the jersey is perfectly suited to competitive races or fast-paced training days while remaining a staple for your everyday summer rides.', 'details',200.00, 'Coral', 'https://assets.pasnormalstudios.com/13640/conversions/Mens-Mechanism-Jersey-Coral_Front-pdp-page.jpg?v=1677745649'),
     ('jersey', 'm', 'Mechanism Jersey', 'Presented in its signature monochrome colourway, the Mechanism Jersey showcases the seamless integration of technical performance with fashionable aesthetics. Defined through its aerodynamic fit and use of lightweight fabric, the jersey is perfectly suited to competitive races or fast-paced training days while remaining a staple for your everyday summer rides.', 'details',200.00, 'Medium Gray', 'https://assets.pasnormalstudios.com/13652/conversions/Mens-Mechanism-Jersey-Grey_Front-pdp-page.jpg?v=1677746987'),
     ('jersey', 'm', 'Mechanism Jersey', 'Presented in its signature monochrome colourway, the Mechanism Jersey showcases the seamless integration of technical performance with fashionable aesthetics. Defined through its aerodynamic fit and use of lightweight fabric, the jersey is perfectly suited to competitive races or fast-paced training days while remaining a staple for your everyday summer rides.', 'details',200.00, 'Burned Orange', 'https://assets.pasnormalstudios.com/10362/conversions/PN_Mechanism_Jersey_Burned-Orange-pdp-page.jpg?v=1668717786'),
     ('jersey', 'm', 'Mechanism Jersey', 'Presented in its signature monochrome colourway, the Mechanism Jersey showcases the seamless integration of technical performance with fashionable aesthetics. Defined through its aerodynamic fit and use of lightweight fabric, the jersey is perfectly suited to competitive races or fast-paced training days while remaining a staple for your everyday summer rides.', 'details',200.00, 'Dark Green', 'https://assets.pasnormalstudios.com/10344/conversions/PN_Mechanism_Jersey_Dark-Green-pdp-page.jpg?v=1668717783'),
     ('jersey', 'm', 'Mechanism Jersey', 'Presented in its signature monochrome colourway, the Mechanism Jersey showcases the seamless integration of technical performance with fashionable aesthetics. Defined through its aerodynamic fit and use of lightweight fabric, the jersey is perfectly suited to competitive races or fast-paced training days while remaining a staple for your everyday summer rides.', 'details',200.00, 'Off White', 'https://assets.pasnormalstudios.com/10353/conversions/PN_Mechanism_Jersey_Off-White_front-pdp-page.jpg?v=1668717783'),
     ('jersey', 'm', 'Mechanism Jersey', 'Presented in its signature monochrome colourway, the Mechanism Jersey showcases the seamless integration of technical performance with fashionable aesthetics. Defined through its aerodynamic fit and use of lightweight fabric, the jersey is perfectly suited to competitive races or fast-paced training days while remaining a staple for your everyday summer rides.', 'details',200.00, 'Purple', 'https://assets.pasnormalstudios.com/267/conversions/Man_Mechanism-Jersey_Purple_4-5-pdp-page.jpg?v=1668716927'),
     ('jersey', 'm', 'Mechanism Jersey', 'Presented in its signature monochrome colourway, the Mechanism Jersey showcases the seamless integration of technical performance with fashionable aesthetics. Defined through its aerodynamic fit and use of lightweight fabric, the jersey is perfectly suited to competitive races or fast-paced training days while remaining a staple for your everyday summer rides.', 'details',200.00, 'Green', 'https://assets.pasnormalstudios.com/6339/conversions/PN_Mechanism_Jersey_Green_4-5-pdp-page.jpg?v=1668717393'),
     ('jersey', 'm', 'Mechanism Long Sleeve Jersey', 'The Mechansim Long Sleeve Jersey is suitable for layering or as a standalone jersey. All through the seasons. The Mechanism Long Sleeve Jersey exhibits the Pas Normal Studios mentality of seamlessly combining visual aesthetics with quality, technical apparel. The soft fleece-backed fabric makes the Mechanism Long Sleeve Jersey perfect for both high-intensity training and racing. Use it as a standalone outer layer on chill mornings or late afternoons. Or pair it with a heavier base layer and a gilet or jacket when the temperature drops.', 'details', 220.00, 'Black/Medium Grey', 'https://assets.pasnormalstudios.com/13810/conversions/Mens-Mechanism-LS-Jersey-Black-Medium-Grey_Front-pdp-page.jpg?v=1677765427'),
     ('jersey', 'm', 'Mechanism Long Sleeve Jersey', 'The Mechansim Long Sleeve Jersey is suitable for layering or as a standalone jersey. All through the seasons. The Mechanism Long Sleeve Jersey exhibits the Pas Normal Studios mentality of seamlessly combining visual aesthetics with quality, technical apparel. The soft fleece-backed fabric makes the Mechanism Long Sleeve Jersey perfect for both high-intensity training and racing. Use it as a standalone outer layer on chill mornings or late afternoons. Or pair it with a heavier base layer and a gilet or jacket when the temperature drops.', 'details', 220.00, 'Deep Red', 'https://assets.pasnormalstudios.com/6442/conversions/PN_Essential_Long_Sleeve_Jersey_DeepRed_4-5-pdp-page.jpg?v=1668717406'),
     ('jersey', 'm', 'Mechanism Long Sleeve Jersey', 'The Mechansim Long Sleeve Jersey is suitable for layering or as a standalone jersey. All through the seasons. The Mechanism Long Sleeve Jersey exhibits the Pas Normal Studios mentality of seamlessly combining visual aesthetics with quality, technical apparel. The soft fleece-backed fabric makes the Mechanism Long Sleeve Jersey perfect for both high-intensity training and racing. Use it as a standalone outer layer on chill mornings or late afternoons. Or pair it with a heavier base layer and a gilet or jacket when the temperature drops.', 'details', 220.00, 'Burned Orange', 'https://assets.pasnormalstudios.com/6450/conversions/PN_Essentiel_Long_Sleeve_Burned-Orange_4-5-pdp-page.jpg?v=1668717407'),
     ('jersey', 'm', 'Mechanism Long Sleeve Jersey', 'The Mechansim Long Sleeve Jersey is suitable for layering or as a standalone jersey. All through the seasons. The Mechanism Long Sleeve Jersey exhibits the Pas Normal Studios mentality of seamlessly combining visual aesthetics with quality, technical apparel. The soft fleece-backed fabric makes the Mechanism Long Sleeve Jersey perfect for both high-intensity training and racing. Use it as a standalone outer layer on chill mornings or late afternoons. Or pair it with a heavier base layer and a gilet or jacket when the temperature drops.', 'details', 220.00, 'Off White', 'https://assets.pasnormalstudios.com/6458/conversions/PN_Essential_Long_Sleeve_Jersey_Off-White_4-5-pdp-page.jpg?v=1668717409'),
     ('jersey', 'm', 'Mechanism Long Sleeve Jersey', 'The Mechansim Long Sleeve Jersey is suitable for layering or as a standalone jersey. All through the seasons. The Mechanism Long Sleeve Jersey exhibits the Pas Normal Studios mentality of seamlessly combining visual aesthetics with quality, technical apparel. The soft fleece-backed fabric makes the Mechanism Long Sleeve Jersey perfect for both high-intensity training and racing. Use it as a standalone outer layer on chill mornings or late afternoons. Or pair it with a heavier base layer and a gilet or jacket when the temperature drops.', 'details', 220.00, 'Dark Grey', 'https://assets.pasnormalstudios.com/6454/conversions/PN_Essentiel_Long_Sleeve_Jersey_DarkGrey_4-5-pdp-page.jpg?v=1668717409'),
     ('jersey', 'm', 'Mechanism Long Sleeve Jersey', 'The Mechansim Long Sleeve Jersey is suitable for layering or as a standalone jersey. All through the seasons. The Mechanism Long Sleeve Jersey exhibits the Pas Normal Studios mentality of seamlessly combining visual aesthetics with quality, technical apparel. The soft fleece-backed fabric makes the Mechanism Long Sleeve Jersey perfect for both high-intensity training and racing. Use it as a standalone outer layer on chill mornings or late afternoons. Or pair it with a heavier base layer and a gilet or jacket when the temperature drops.', 'details', 220.00, 'Olive', 'https://assets.pasnormalstudios.com/6858/conversions/LongSleeveJersey_Olive_4-5-pdp-page.jpg?v=1668717460'),
     ('jersey', 'm', 'Mechanism Long Sleeve Jersey', 'The Mechansim Long Sleeve Jersey is suitable for layering or as a standalone jersey. All through the seasons. The Mechanism Long Sleeve Jersey exhibits the Pas Normal Studios mentality of seamlessly combining visual aesthetics with quality, technical apparel. The soft fleece-backed fabric makes the Mechanism Long Sleeve Jersey perfect for both high-intensity training and racing. Use it as a standalone outer layer on chill mornings or late afternoons. Or pair it with a heavier base layer and a gilet or jacket when the temperature drops.', 'details', 220.00, 'Off White Charcoal', 'https://assets.pasnormalstudios.com/11035/conversions/Men%27s-Mechanism-Long-Sleeve-Jersey-Off-White---Black_Front-pdp-page.jpg?v=1668717864'),
     ('jersey', 'm', 'Mechanism Long Sleeve Jersey', 'The Mechansim Long Sleeve Jersey is suitable for layering or as a standalone jersey. All through the seasons. The Mechanism Long Sleeve Jersey exhibits the Pas Normal Studios mentality of seamlessly combining visual aesthetics with quality, technical apparel. The soft fleece-backed fabric makes the Mechanism Long Sleeve Jersey perfect for both high-intensity training and racing. Use it as a standalone outer layer on chill mornings or late afternoons. Or pair it with a heavier base layer and a gilet or jacket when the temperature drops.', 'details', 220.00, 'Olive Brown', 'https://assets.pasnormalstudios.com/11023/conversions/Mens-Mechanism-Long-sleeve-Jersey-Brown-Olive_Front-pdp-page.jpg?v=1668717861'),
     ('jersey', 'm', 'Mechanism Long Sleeve Jersey', 'The Mechansim Long Sleeve Jersey is suitable for layering or as a standalone jersey. All through the seasons. The Mechanism Long Sleeve Jersey exhibits the Pas Normal Studios mentality of seamlessly combining visual aesthetics with quality, technical apparel. The soft fleece-backed fabric makes the Mechanism Long Sleeve Jersey perfect for both high-intensity training and racing. Use it as a standalone outer layer on chill mornings or late afternoons. Or pair it with a heavier base layer and a gilet or jacket when the temperature drops.', 'details', 220.00, 'Dusty Navy', 'https://assets.pasnormalstudios.com/11114/conversions/PN_MensMechanismLongSleeveJersey_DustyNavy-pdp-page.jpg?v=1668717873'),
     ('jersey', 'm', 'Mechanism Long Sleeve Jersey', 'The Mechansim Long Sleeve Jersey is suitable for layering or as a standalone jersey. All through the seasons. The Mechanism Long Sleeve Jersey exhibits the Pas Normal Studios mentality of seamlessly combining visual aesthetics with quality, technical apparel. The soft fleece-backed fabric makes the Mechanism Long Sleeve Jersey perfect for both high-intensity training and racing. Use it as a standalone outer layer on chill mornings or late afternoons. Or pair it with a heavier base layer and a gilet or jacket when the temperature drops.', 'details', 220.00, 'Black', 'https://assets.pasnormalstudios.com/6847/conversions/Men_LongSleeveJersey_Black_4-5-pdp-page.jpg?v=1668717457'),
     ('jersey', 'm', 'Mechanism Long Sleeve Jersey', 'The Mechansim Long Sleeve Jersey is suitable for layering or as a standalone jersey. All through the seasons. The Mechanism Long Sleeve Jersey exhibits the Pas Normal Studios mentality of seamlessly combining visual aesthetics with quality, technical apparel. The soft fleece-backed fabric makes the Mechanism Long Sleeve Jersey perfect for both high-intensity training and racing. Use it as a standalone outer layer on chill mornings or late afternoons. Or pair it with a heavier base layer and a gilet or jacket when the temperature drops.', 'details', 220.00, 'Anthracite', 'https://assets.pasnormalstudios.com/11020/conversions/Men%27s-Mechanism-Long-Sleeve-Jersey-Black_Front-pdp-page.jpg?v=1668717861'),
     ('jersey', 'm', 'Mechanism Long Sleeve Jersey', 'The Mechansim Long Sleeve Jersey is suitable for layering or as a standalone jersey. All through the seasons. The Mechanism Long Sleeve Jersey exhibits the Pas Normal Studios mentality of seamlessly combining visual aesthetics with quality, technical apparel. The soft fleece-backed fabric makes the Mechanism Long Sleeve Jersey perfect for both high-intensity training and racing. Use it as a standalone outer layer on chill mornings or late afternoons. Or pair it with a heavier base layer and a gilet or jacket when the temperature drops.', 'details', 220.00, 'Dark Navy/Dusty Mauve', 'https://assets.pasnormalstudios.com/13819/conversions/Mens-Mechanism-LS-Jersey-Dark-Navy-Dusty-Mauve_Front-pdp-page.jpg?v=1677765788')
     ;


    --  ('jersey', 'm', 'name', 'description', 'details',155.00, 'color', 'url'),
